---
apiVersion: v1
kind: Namespace
metadata:
  name: rotate-certs

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rotate-certs
  namespace: rotate-certs

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rotate-certs-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: rotate-certs
  namespace: rotate-certs
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

